In [2]:
import requests
import pandas as pd
from matplotlib import pyplot as plt
from scipy.stats import gamma
import numpy as np
import c3aidatalake

In [60]:
locations = c3aidatalake.fetch(
    'outbreaklocation',
    {
        'spec': {
            'filter': 'id == "Orange_Florida_UnitedStates"'
        }
    }
)

locations

,hospitalIcuBeds,hospitalStaffedBeds,hospitalLicensedBeds,latestTotalPopulation,populationOfAllChildren,latestLaborForce,latestEmployedPopulation,latestUnemployedPopulation,latestUnemploymentRate,laborForceOfAllChildren,locationType,populationCDS,id,name,typeIdent,location.value.id,location.timestamp,fips.id
0,349,4291,3043,1393452.0,1393452.0,728005,675329,52676,7.235665,728005,county,1393452,Orange_Florida_UnitedStates,Orange,EP_LOC,Orange_Florida_UnitedStates,2021-03-01T00:00:00Z,12095

In [35]:
trials = c3aidatalake.evalmetrics(
    'outbreaklocation',
    {
        'spec': {
            'ids': ['Texas_UnitedStates'],
            'expressions': ['JHU_ConfirmedCases'],
            'start': '2021-01-01',
            'end': '2021-02-28',
            'interval': 'DAY',
        }
    }
)

trials

,dates,Texas_UnitedStates.JHU_ConfirmedCases.data,Texas_UnitedStates.JHU_ConfirmedCases.missing
0,2021-01-01,1.7796e+06,0
0,2021-01-02,1.79345e+06,0
0,2021-01-03,1.81032e+06,0
0,2021-01-04,1.8292e+06,0
0,2021-01-05,1.86076e+06,0
0,2021-01-06,1.8848e+06,0
0,2021-01-07,1.91009e+06,0
0,2021-01-08,1.9234e+06,0
0,2021-01-09,1.95192e+06,0
0,2021-01-10,1.96819e+06,0
0,2021-01-11,1.9902e+06,0
0,2021-01-12,2.01464e+06,0
0,2021-01-13,2.04075e+06,0
0,2021-01-14,2.06864e+06,0
0,2021-01-15,2.06929e+06,0
0,2021-01-16,2.11266e+06,0
0,2021-01-17,2.12711e+06,0
0,2021-01-18,2.13819e+06,0
0,2021-01-19,2.15746e+06,0
0,2021-01-20,2.18555e+06,0
0,2021-01-21,2.20887e+06,0
0,2021-01-22,2.22779e+06,0
0,2021-01-23,2.24247e+06,0
0,2021-01-24,2.25042e+06,0
0,2021-01-25,2.26942e+06,0
0,2021-01-26,2.29062e+06,0
0,2021-01-27,2.30922e+06,0
0,2021-01-28,2.33027e+06,0
0,2021-01-29,2.34819e+06,0
0,2021-01-30,2.36327e+06,0
0,2021-01-31,2.37634e+06,0
0,2021-02-01,2.41263e+06,0
0,2021-02-02,2.43169e+06,0
0,2021-02-03,2.44954e+06,0
0,2021-02-04,2.46342e+06,0
0,2021-02-05,2.478e+06,0
0,2021-02-06,2.48650e+06,0
0,2021-02-07,2.49486e+06,0
0,2021-02-08,2.50458e+06,0
0,2021-02-09,2.51833e+06,0
0,2021-02-10,2.53106e+06,0
0,2021-02-11,2.54324e+06,0
0,2021-02-12,2.55484e+06,0
0,2021-02-13,2.56039e+06,0
0,2021-02-14,2.56526e+06,0
0,2021-02-15,2.56804e+06,0
0,2021-02-16,2.57096e+06,0
0,2021-02-17,2.5761e+06,0
0,2021-02-18,2.5784e+06,0
0,2021-02-19,2.58771e+06,0
0,2021-02-20,2.59382e+06,0
0,2021-02-21,2.60066e+06,0
0,2021-02-22,2.60651e+06,0
0,2021-02-23,2.6171e+06,0
0,2021-02-24,2.62485e+06,0
0,2021-02-25,2.63267e+06,0
0,2021-02-26,2.64346e+06,0
0,2021-02-27,2.64936e+06,0

In [9]:
vaccine = c3aidatalake.fetch(
    'vaccinecoverage',
    {
        'spec': {}
    }
)

vaccine

,vaxView,year,timestamp,value,lowerLimit,upperLimit,sampleSize,confidenceInterval,vaccineDetails,demographicClass,demographicClassDetails,id,location.id,target,totalPopulation,surveyType,other,difference,kindergartenPopulation,percentSurveyed
0,Child,2001,2001-01-01T00:00:00Z,92.2,89.1,94.4,562.0,2.7,>=3 doses Hib Vaccination,Age,24 Months,00000cba-509c-4504-b1f7-ccd44cfe6b42,Indiana_UnitedStates,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Child,2003,2003-01-01T00:00:00Z,77.3,61.4,87.9,54.0,13.3,Combined 4 Series Vaccination,Facility Type,Other,00001124-80e5-4c0e-9269-60331d7113eb,NewMexico_UnitedStates,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Child,2010,2010-01-01T00:00:00Z,75.7,68.5,81.7,332.0,6.6,>=4 doses PCV Vaccination,Age,19 Months,00001dc5-f5fa-499e-bdf5-8d6261e85833,NewJersey_UnitedStates,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Child,2017,2017-01-01T00:00:00Z,76.9,75.3,78.5,11392.0,1.6,Combined 5 Series Vaccination,Poverty,Living At or Above Poverty,00004b3a-28f5-4b34-a998-1833a1aded32,UnitedStates,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Influenza,2015,2015-01-01T00:00:00Z,45.3,38.1,52.5,461.0,7.2,Influenza vaccination (General Population),Age,13-17 years,00006fab-7d97-4bb7-ade2-0fb8beefce45,Kentucky_UnitedStates,70.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Influenza,2010,2010-01-01T00:00:00Z,NaN,NaN,NaN,NaN,NaN,Influenza vaccination (Nursing Home),Marital Status,Separated,00ac4f03-3960-4c9e-8509-b2b4477741e9,Region2_UnitedStates,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1996,Child,2014,2014-01-01T00:00:00Z,57.8,44.6,70.1,83.0,13.0,Rotavirus Vaccination,Poverty,Living Below Poverty,00ac5fca-5dd3-4462-8824-773c358656b3,CityofNewYork_NewYork_UnitedStates,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1997,Child,2000,2000-01-01T00:00:00Z,94.5,91.2,96.6,230.0,2.6,>=3 doses Hib Vaccination,Facility Type,Other,00ac6649-23e7-4d39-b8cd-1db9c8b67f0c,Ohio_UnitedStates,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998,Teenager,2015,2015-01-01T00:00:00Z,48.5,39.6,57.5,174.0,9.0,"Sociodemographic Characteristics, Male",Urbanicity,Living in an MSA Central City,00ac6915-9159-4174-911e-3ae2928589ef,Colorado_UnitedStates,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999,Child,2008,2008-01-01T00:00:00Z,93.6,81.1,98.0,30.0,7.3,>=3 doses PCV Vaccination,Race/Ethnicity,Hispanic,00ac772b-b7f2-4c59-850b-aaacea440ea1,DistrictofColumbia_UnitedStates,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
patients = c3aidatalake.fetch(
    'vaccinecoverage',
    {
        'spec': {
            'filter': 'symptoms != ""'
        }
    }
)

patients.loc[patients.didDie == True]